version: '2.1'
volumes:
  cups:
services:
  cups:
    build: ./cups
    ports:
      - "80"
    privileged: true
    restart: always
    network_mode: host
    volumes:
      - 'cups:/etc/cups'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
  # mdns-publisher:
  #   build: ./mdns-publisher
  #   restart: always
  #   environment:
  #     DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'